# Generated by Django 5.0.3 on 2024-05-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='C:/Users/SBG/OneDrive/Documents/Bureau/APPMOBILEstore/product/images'),
        ),
    ]
